export const images = {
  bgGameCardPlay: require('@/assets/images/bg_game_card_play.png'),
  bgGameColorPlay: require('@/assets/images/bg_game_color_play.png'),
  gameFlipCard: require('@/assets/images/game_flip_card.png'),
  gameFindColor: require('@/assets/images/game_find_color.png'),
  cao_thu: require('~/assets/images/achievement/cao_thu.png'),
  cham_chi: require('~/assets/images/achievement/cham_chi.png'),
  hoan_hao: require('~/assets/images/achievement/hoan_hao.png'),
  khong_the_can_pha: require('~/assets/images/achievement/khong_the_can_pha.png'),
  sieu_nhi: require('~/assets/images/achievement/sieu_nhi.png'),
  tan_binh: require('~/assets/images/achievement/tan_binh.png'),
  toc_do: require('~/assets/images/achievement/toc_do.png'),
  cards: require('@/assets/images/cards.png'),
  splash: require('@/assets/images/splash.png'),
  bgHome: require('@/assets/images/bg_home.png'),
  bgSelectMode: require('@/assets/images/bg_select_mode.png'),
  logoApp: require('@/assets/images/logo_app.png'),
  rope: require('@/assets/images/rope.png'),
  bgMode: require('@/assets/images/bg_mode.png'),
  bgFlipCard: require('@/assets/images/bg_game_flip_card.png'),
  bgColor: require('@/assets/images/bg_game_color.png'),
  bgBoard: require('@/assets/images/bg_board.png'),
  levelGame: require('@/assets/images/level_game.png'),
  bgAchievement: require('@/assets/images/bg_achievement.png'),
  bgAchievement2: require('@/assets/images/bg_achievement2.png'),
  bgTutorial: require('@/assets/images/bg_tutorial.png'),
  boardTimeLine: require('@/assets/images/board_time_line.png'),
  cardActive: require('@/assets/images/icon_card_active.png'),
  cardDeActive: require('@/assets/images/icon_card_de_active.png'),
  iconStarActive: require('@/assets/images/star-level/icon_star_active.png'),
  iconStarDeActive: require('@/assets/images/star-level/icon_star_de_active.png'),
  bgModal: require('@/assets/images/bg_modal.png'),
  timeProcessBar: require('@/assets/images/time_duration.png'),
  starLeft: require('@/assets/images/star-result/star_left.png'),
  starRight: require('@/assets/images/star-result/star_right.png'),
  starCenter: require('@/assets/images/star-result/star_center.png'),
  starLeftActive: require('@/assets/images/star-result/star_left_active.png'),
  starRightActive: require('@/assets/images/star-result/star_right_active.png'),
  starCenterActive: require('@/assets/images/star-result/star_center_active.png'),
} as const //

export type ImageKeys = keyof typeof images // Tạo type dựa trên key của `images`

export default images
